services:
  espocrm-db:
    image: mariadb:latest
    container_name: espocrm-db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: database_password
    volumes:
      - espocrm-db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    depends_on:
      - espocrm-db
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://132.145.56.82:8080"
    volumes:
      - espocrm:/var/www/html
      - ./custom/Espo:/var/www/html/custom/Espo
      - ./client-custom:/var/www/html/client/custom
    restart: always
    ports:
      - "8080:80"

volumes:
  espocrm-db:
  espocrm:
